/**
 * egdesk.schema.ts — committed seed schema
 *
 * COMMIT THIS FILE TO GIT.
 *
 * When someone opens this project in their EGDesk, these tables are created
 * automatically in their dev database on first server start.
 *
 * Unlike egdesk.config.ts (auto-generated, gitignored), this file is the
 * portable source of truth for your app's database structure.
 *
 * Edit this file when you add/remove tables or columns. Do NOT edit
 * egdesk.config.ts — EGDesk regenerates it from the live database.
 */

export const TABLES = {
  crm_credential_audit_logs: {
    name: 'crm_credential_audit_logs',
    displayName: '보안 인증 감사록',
    columns: ['credential_id', 'operator_id', 'operator_name', 'action_type', 'access_reason', 'created_at', 'uuid', 'updated_at', 'updated_by', 'deleted_at', 'deleted_by', 'restored_at', 'restored_by'],
    columnCount: 13,
    rowCount: 0,
  },
  crm_credential_emergency_requests: {
    name: 'crm_credential_emergency_requests',
    displayName: '보안 인증 비상 요청 대장',
    columns: ['credential_id', 'requester_id', 'request_reason', 'status', 'approved_by', 'approved_at', 'expires_at', 'created_at', 'uuid', 'updated_at', 'updated_by', 'deleted_at', 'deleted_by', 'restored_at', 'restored_by'],
    columnCount: 15,
    rowCount: 0,
  },
  crm_credential_vault: {
    name: 'crm_credential_vault',
    displayName: '보안 인증 정보 금고',
    columns: ['category', 'asset_name', 'login_id', 'encrypted_password', 'iv', 'auth_tag', 'remarks', 'owner_operator_id', 'status', 'created_at', 'updated_at', 'uuid', 'updated_by', 'deleted_at', 'deleted_by', 'restored_at', 'restored_by'],
    columnCount: 17,
    rowCount: 0,
  },
  rnd_compliance_alarms: {
    name: 'rnd_compliance_alarms',
    displayName: '규제 준수 모니터링 및 알림',
    columns: ['alarm_id', 'center_id', 'category', 'severity', 'message', 'due_date', 'is_resolved', 'resolved_at', 'created_at', 'uuid', 'updated_at', 'updated_by', 'deleted_at', 'deleted_by', 'restored_at', 'restored_by'],
    columnCount: 16,
    rowCount: 0,
  },
  rnd_logs: {
    name: 'rnd_logs',
    displayName: 'R&D 연구개발 일지 및 AI 생성 데이터',
    columns: ['log_id', 'center_id', 'author_id', 'work_date', 'raw_source', 'raw_content', 'audio_file_url', 'ai_generated_title', 'ai_generated_content', 'approval_status', 'approver_id', 'approved_at', 'blockchain_hash', 'created_at', 'updated_at', 'uuid', 'updated_by', 'deleted_at', 'deleted_by', 'restored_at', 'restored_by'],
    columnCount: 21,
    rowCount: 0,
  },
  rnd_spaces: {
    name: 'rnd_spaces',
    displayName: '연구 공간 자가 실사 및 Vision AI 분석 이력',
    columns: ['space_check_id', 'center_id', 'check_date', 'image_url_entrance', 'image_url_layout', 'ai_analysis_result', 'signage_status', 'partition_status', 'overall_status', 'inspector_notes', 'created_at', 'uuid', 'updated_at', 'updated_by', 'deleted_at', 'deleted_by', 'restored_at', 'restored_by'],
    columnCount: 18,
    rowCount: 0,
  },
  rnd_staffs: {
    name: 'rnd_staffs',
    displayName: '연구원 정보 및 자격 정보',
    columns: ['staff_id', 'center_id', 'user_id', 'staff_role', 'employment_status', 'degree_level', 'major_name', 'major_category', 'graduation_cert_ocr_json', 'qualification_status', 'joined_date', 'resigned_date', 'uuid', 'updated_at', 'updated_by', 'deleted_at', 'deleted_by', 'restored_at', 'restored_by'],
    columnCount: 19,
    rowCount: 0,
  },
  rnd_centers: {
    name: 'rnd_centers',
    displayName: '기업부설연구소 기본 정보',
    columns: ['center_id', 'company_id', 'center_name', 'center_type', 'established_date', 'koita_reg_number', 'postal_code', 'address_road', 'address_detail', 'total_area_sqm', 'is_active', 'uuid', 'updated_at', 'updated_by', 'deleted_at', 'deleted_by', 'restored_at', 'restored_by'],
    columnCount: 18,
    rowCount: 0,
  },
  crm_facility_predictive_part_rul: {
    name: 'crm_facility_predictive_part_rul',
    displayName: '설비 부품 수명 RUL',
    columns: ['equipmentId', 'partName', 'rulDays', 'status', 'percent', 'uuid', 'updated_at', 'updated_by', 'deleted_at', 'deleted_by', 'restored_at', 'restored_by'],
    columnCount: 12,
    rowCount: 0,
  },
  crm_facility_predictive_fft: {
    name: 'crm_facility_predictive_fft',
    displayName: '설비 주파수 분석',
    columns: ['equipmentId', 'frequency', 'amplitude', 'label', 'uuid', 'updated_at', 'updated_by', 'deleted_at', 'deleted_by', 'restored_at', 'restored_by'],
    columnCount: 11,
    rowCount: 0,
  },
  crm_facility_predictive_vibration: {
    name: 'crm_facility_predictive_vibration',
    displayName: '설비 진동 센서 이력',
    columns: ['equipmentId', 'time', 'value', 'uuid', 'updated_at', 'updated_by', 'deleted_at', 'deleted_by', 'restored_at', 'restored_by'],
    columnCount: 10,
    rowCount: 0,
  },
  crm_facility_predictive_summary: {
    name: 'crm_facility_predictive_summary',
    displayName: '설비 건전도 요약',
    columns: ['equipmentId', 'equipmentName', 'healthScore', 'vibrationRms', 'uuid', 'updated_at', 'updated_by', 'deleted_at', 'deleted_by', 'restored_at', 'restored_by'],
    columnCount: 11,
    rowCount: 0,
  },
  crm_facility_repair_solutions: {
    name: 'crm_facility_repair_solutions',
    displayName: '설비 고장 해결 가이드',
    columns: ['errorCode', 'rootCause', 'actions', 'similarHistory', 'warehouse', 'uuid', 'updated_at', 'updated_by', 'deleted_at', 'deleted_by', 'restored_at', 'restored_by'],
    columnCount: 12,
    rowCount: 0,
  },
  crm_facility_repair_logs: {
    name: 'crm_facility_repair_logs',
    displayName: '설비 수리 이력 대장',
    columns: ['date', 'equipmentId', 'equipmentName', 'errorCode', 'symptom', 'repairDesc', 'mechanic', 'cost', 'uuid', 'updated_at', 'updated_by', 'deleted_at', 'deleted_by', 'restored_at', 'restored_by'],
    columnCount: 15,
    rowCount: 0,
  },
  crm_facility_checklists: {
    name: 'crm_facility_checklists',
    displayName: '설비 예방 점검 이력',
    columns: ['equipmentId', 'inspector', 'checks', 'signatureData', 'audioUrl', 'status', 'checkedAt', 'uuid', 'updated_at', 'updated_by', 'deleted_at', 'deleted_by', 'restored_at', 'restored_by'],
    columnCount: 14,
    rowCount: 0,
  },
  crm_facilities: {
    name: 'crm_facilities',
    displayName: '설비 대장 관리',
    columns: ['name', 'manufacturer', 'model_name', 'serial_number', 'manufacture_year', 'specifications', 'location', 'status', 'health_score', 'vibration_rms', 'created_at', 'updated_at', 'uuid', 'updated_by', 'deleted_at', 'deleted_by', 'restored_at', 'restored_by'],
    columnCount: 18,
    rowCount: 0,
  },
  crm_quality_vision_logs: {
    name: 'crm_quality_vision_logs',
    displayName: '품질 비전 판정 이력',
    columns: ['timestamp', 'itemName', 'anomalyScore', 'status', 'defectType', 'imageUrl', 'isReviewed', 'uuid', 'updated_at', 'updated_by', 'deleted_at', 'deleted_by', 'restored_at', 'restored_by'],
    columnCount: 14,
    rowCount: 0,
  },
  crm_quality_vision_model: {
    name: 'crm_quality_vision_model',
    displayName: '품질 비전 AI 모델 상태',
    columns: ['activeModel', 'goldenSamplesCount', 'lastTrainedAt', 'anomalyThreshold', 'uuid', 'updated_at', 'updated_by', 'deleted_at', 'deleted_by', 'restored_at', 'restored_by'],
    columnCount: 11,
    rowCount: 0,
  },
  crm_quality_spc_features: {
    name: 'crm_quality_spc_features',
    displayName: 'SPC 요인 중요도',
    columns: ['name', 'value', 'color', 'uuid', 'updated_at', 'updated_by', 'deleted_at', 'deleted_by', 'restored_at', 'restored_by'],
    columnCount: 10,
    rowCount: 0,
  },
  crm_quality_spc_predictions: {
    name: 'crm_quality_spc_predictions',
    displayName: 'SPC 계측 예측',
    columns: ['batch', 'value', 'cpk', 'timestamp', 'risk', 'uuid', 'updated_at', 'updated_by', 'deleted_at', 'deleted_by', 'restored_at', 'restored_by'],
    columnCount: 12,
    rowCount: 0,
  },
  crm_quality_spc_samples: {
    name: 'crm_quality_spc_samples',
    displayName: 'SPC 계측 샘플',
    columns: ['batch', 'value', 'cpk', 'timestamp', 'uuid', 'updated_at', 'updated_by', 'deleted_at', 'deleted_by', 'restored_at', 'restored_by'],
    columnCount: 11,
    rowCount: 0,
  },
  crm_quality_spc_config: {
    name: 'crm_quality_spc_config',
    displayName: 'SPC 공정 제어 설정',
    columns: ['targetValue', 'ucl', 'lcl', 'usl', 'lsl', 'currentCpk', 'cpkStatus', 'futureRiskProbability', 'uuid', 'updated_at', 'updated_by', 'deleted_at', 'deleted_by', 'restored_at', 'restored_by'],
    columnCount: 15,
    rowCount: 0,
  },
  crm_quality_sensors_timeline: {
    name: 'crm_quality_sensors_timeline',
    displayName: '센서 시계열',
    columns: ['time', 'vibration', 'current', 'temperature', 'anomalyScore', 'uuid', 'updated_at', 'updated_by', 'deleted_at', 'deleted_by', 'restored_at', 'restored_by'],
    columnCount: 12,
    rowCount: 0,
  },
  crm_quality_sensors_contribution: {
    name: 'crm_quality_sensors_contribution',
    displayName: '센서 기여도',
    columns: ['name', 'rate', 'uuid', 'updated_at', 'updated_by', 'deleted_at', 'deleted_by', 'restored_at', 'restored_by'],
    columnCount: 9,
    rowCount: 0,
  },
  crm_quality_sensors_status: {
    name: 'crm_quality_sensors_status',
    displayName: '설비 센서 상태',
    columns: ['equipmentName', 'operationalStatus', 'vibrationRms', 'motorCurrent', 'bearingTemp', 'anomalyScore', 'threshold', 'uuid', 'updated_at', 'updated_by', 'deleted_at', 'deleted_by', 'restored_at', 'restored_by'],
    columnCount: 14,
    rowCount: 0,
  },
  crm_quality_ncr_similar_cases: {
    name: 'crm_quality_ncr_similar_cases',
    displayName: '유사 NCR 사례',
    columns: ['title', 'similarity', 'rootCause', 'actionTaken', 'uuid', 'updated_at', 'updated_by', 'deleted_at', 'deleted_by', 'restored_at', 'restored_by'],
    columnCount: 11,
    rowCount: 0,
  },
  crm_quality_ncr_items: {
    name: 'crm_quality_ncr_items',
    displayName: 'NCR 부적합 내역',
    columns: ['date', 'itemName', 'defectCode', 'defectType', 'quantity', 'reporter', 'status', 'description', 'actionPlan', 'uuid', 'updated_at', 'updated_by', 'deleted_at', 'deleted_by', 'restored_at', 'restored_by'],
    columnCount: 16,
    rowCount: 0,
  },
  crm_quality_checklist_submissions: {
    name: 'crm_quality_checklist_submissions',
    displayName: '체크리스트 제출 내역',
    columns: ['lotNo', 'inspector', 'checkItems', 'signatureData', 'photoUrl', 'status', 'submittedAt', 'uuid', 'updated_at', 'updated_by', 'deleted_at', 'deleted_by', 'restored_at', 'restored_by'],
    columnCount: 14,
    rowCount: 0,
  },
  crm_grant_company_profile: {
    name: 'crm_grant_company_profile',
    displayName: '지원금 매칭용 기업 프로필',
    columns: ['establishmentYear', 'employeeCount', 'patentsCount', 'femaleEmployeeRatio', 'youthEmployeeRatio', 'sector', 'uuid', 'updated_at', 'updated_by', 'deleted_at', 'deleted_by', 'restored_at', 'restored_by'],
    columnCount: 13,
    rowCount: 0,
  },
  crm_grant_rnd_plans: {
    name: 'crm_grant_rnd_plans',
    displayName: '지원금 R&D 계획서',
    columns: ['announcement_id', 'plan_data', 'uuid', 'updated_at', 'updated_by', 'deleted_at', 'deleted_by', 'restored_at', 'restored_by'],
    columnCount: 9,
    rowCount: 0,
  },
  crm_grant_bookmarks: {
    name: 'crm_grant_bookmarks',
    displayName: '지원금 북마크',
    columns: ['announcement_id', 'uuid', 'updated_at', 'updated_by', 'deleted_at', 'deleted_by', 'restored_at', 'restored_by'],
    columnCount: 8,
    rowCount: 0,
  },
  crm_grant_announcements: {
    name: 'crm_grant_announcements',
    displayName: '정부 지원금 추천 공고',
    columns: ['title', 'agency', 'match_score', 'match_guide', 'budget', 'end_date', 'uuid', 'updated_at', 'updated_by', 'deleted_at', 'deleted_by', 'restored_at', 'restored_by'],
    columnCount: 13,
    rowCount: 0,
  },
  crm_recruitment_applicants: {
    name: 'crm_recruitment_applicants',
    displayName: '채용 지원자 관리',
    columns: ['name', 'age', 'phone', 'experience', 'motivation', 'matching_score', 'status', 'signature_url', 'signed_at', 'resume_file_path', 'tech_stacks', 'interview_logs', 'ai_evaluation', 'created_at', 'uuid', 'updated_at', 'updated_by', 'deleted_at', 'deleted_by', 'restored_at', 'restored_by'],
    columnCount: 21,
    rowCount: 0,
  },
  crm_financial_statements: {
    name: 'crm_financial_statements',
    displayName: '재무제표 관리',
    columns: ['company_id', 'company_type', 'fiscal_year', 'fiscal_quarter', 'total_assets', 'total_liabilities', 'total_equity', 'revenue', 'operating_income', 'net_income', 'pdf_file_path', 'parsed_raw_json', 'created_at', 'updated_at', 'uuid', 'updated_by', 'deleted_at', 'deleted_by', 'restored_at', 'restored_by'],
    columnCount: 20,
    rowCount: 0,
  },
  safety_inspect_logs: {
    name: 'safety_inspect_logs',
    displayName: '안전점검 감사 대장',
    columns: ['inspect_title', 'inspect_date', 'inspector_name', 'checklist_json', 'fail_actions_json', 'created_at', 'uuid', 'updated_at', 'updated_by', 'deleted_at', 'deleted_by', 'restored_at', 'restored_by'],
    columnCount: 13,
    rowCount: 0,
  },
  safety_near_misses: {
    name: 'safety_near_misses',
    displayName: '아차사고 및 유해요소 제보 대장',
    columns: ['reporter_name', 'hazard_location', 'description', 'photo_url', 'risk_grade', 'action_status', 'action_description', 'action_photo_url', 'action_completed_at', 'created_at', 'uuid', 'updated_at', 'updated_by', 'deleted_at', 'deleted_by', 'restored_at', 'restored_by'],
    columnCount: 17,
    rowCount: 0,
  },
  safety_tbm_logs: {
    name: 'safety_tbm_logs',
    displayName: 'TBM 안전 교육 대장',
    columns: ['tbm_date', 'work_leader', 'weather_info', 'tbm_script', 'attendees_count', 'attendee_signatures', 'created_at', 'uuid', 'updated_at', 'updated_by', 'deleted_at', 'deleted_by', 'restored_at', 'restored_by'],
    columnCount: 14,
    rowCount: 0,
  },
  safety_risk_assessments: {
    name: 'safety_risk_assessments',
    displayName: 'AI 위험성평가서',
    columns: ['work_name', 'work_date', 'hazards_json', 'risk_level', 'evaluated_by', 'approved_at', 'status', 'uuid', 'updated_at', 'updated_by', 'deleted_at', 'deleted_by', 'restored_at', 'restored_by'],
    columnCount: 14,
    rowCount: 0,
  },
  safety_policies: {
    name: 'safety_policies',
    displayName: '안전보건방침 및 목표',
    columns: ['year', 'policy_title', 'targets_json', 'established_at', 'established_by', 'uuid', 'updated_at', 'updated_by', 'deleted_at', 'deleted_by', 'restored_at', 'restored_by'],
    columnCount: 12,
    rowCount: 0,
  },
  crm_employment_certificate_logs: {
    name: 'crm_employment_certificate_logs',
    displayName: '재직증명서 발급대장',
    columns: ['staff_id', 'staff_name', 'joined_date', 'degree_level', 'major_name', 'address', 'usage', 'issue_date', 'issue_dept', 'issue_by', 'extra_data', 'uuid', 'updated_at', 'updated_by', 'deleted_at', 'deleted_by', 'restored_at', 'restored_by'],
    columnCount: 18,
    rowCount: 0,
  },
  form_mappings: {
    name: 'form_mappings',
    displayName: '양식 데이터 필드 매핑',
    columns: ['template_id', 'field_key', 'field_label', 'pos_x', 'pos_y', 'font_size', 'font_weight', 'text_align', 'uuid', 'updated_at', 'updated_by', 'deleted_at', 'deleted_by', 'restored_at', 'restored_by'],
    columnCount: 15,
    rowCount: 0,
  },
  form_templates: {
    name: 'form_templates',
    displayName: '양식 템플릿 마스터',
    columns: ['template_name', 'document_type', 'file_path', 'orientation', 'is_active', 'query_sql', 'query_params', 'uuid', 'updated_at', 'updated_by', 'deleted_at', 'deleted_by', 'restored_at', 'restored_by'],
    columnCount: 14,
    rowCount: 0,
  },
  ai_contextual_help: {
    name: 'ai_contextual_help',
    displayName: 'AI 도움말 캐시',
    columns: ['hint_key', 'hint_text', 'ai_explanation', 'created_at', 'uuid', 'updated_at', 'updated_by', 'deleted_at', 'deleted_by', 'restored_at', 'restored_by'],
    columnCount: 11,
    rowCount: 0,
  },
  system_mail_logs: {
    name: 'system_mail_logs',
    displayName: '메일 AI 관제 로그',
    columns: ['sender', 'subject', 'received_at', 'ai_summary', 'intent', 'risk_level', 'action_type', 'action_result', 'created_at', 'uuid', 'updated_at', 'updated_by', 'deleted_at', 'deleted_by', 'restored_at', 'restored_by'],
    columnCount: 16,
    rowCount: 0,
  },
  system_menu_settings: {
    name: 'system_menu_settings',
    displayName: '시스템 메뉴 설정',
    columns: ['menu_href', 'is_enabled', 'sort_order', 'uuid', 'updated_at', 'updated_by', 'deleted_at', 'deleted_by', 'restored_at', 'restored_by'],
    columnCount: 10,
    rowCount: 0,
  },
  shared_dashboards: {
    name: 'shared_dashboards',
    displayName: '공유 대시보드 관리',
    columns: ['share_id', 'title', 'sql_query', 'table_name', 'display_name', 'chart_spec_json', 'briefing_markdown', 'refresh_interval', 'last_refreshed_at', 'created_at', 'is_active', 'sort_order', 'is_pinned', 'custom_title', 'uuid', 'updated_at', 'updated_by', 'deleted_at', 'deleted_by', 'restored_at', 'restored_by'],
    columnCount: 21,
    rowCount: 0,
  },
  expense_projects: {
    name: 'expense_projects',
    displayName: '지출 프로젝트 관리',
    columns: ['name', 'created_at', 'uuid', 'updated_at', 'updated_by', 'deleted_at', 'deleted_by', 'restored_at', 'restored_by'],
    columnCount: 9,
    rowCount: 0,
  },
  expense_employees: {
    name: 'expense_employees',
    displayName: '지출 임직원 관리',
    columns: ['name', 'created_at', 'uuid', 'updated_at', 'updated_by', 'deleted_at', 'deleted_by', 'restored_at', 'restored_by'],
    columnCount: 9,
    rowCount: 0,
  },
  expense_departments: {
    name: 'expense_departments',
    displayName: '지출 부서 관리',
    columns: ['name', 'created_at', 'uuid', 'updated_at', 'updated_by', 'deleted_at', 'deleted_by', 'restored_at', 'restored_by'],
    columnCount: 9,
    rowCount: 0,
  },
  expense_tags: {
    name: 'expense_tags',
    displayName: '통합 공통 태그 관리',
    columns: ['name', 'scope', 'created_at', 'uuid', 'updated_at', 'updated_by', 'deleted_at', 'deleted_by', 'restored_at', 'restored_by'],
    columnCount: 10,
    rowCount: 0,
  },
  expense_categories: {
    name: 'expense_categories',
    displayName: '지출 계정과목 관리',
    columns: ['main_category', 'mid_category', 'sub_category', 'created_at', 'uuid', 'updated_at', 'updated_by', 'deleted_at', 'deleted_by', 'restored_at', 'restored_by'],
    columnCount: 11,
    rowCount: 0,
  },
  expense_settings: {
    name: 'expense_settings',
    displayName: '지출 예산 설정',
    columns: ['monthly_budget', 'is_alert_enabled', 'alert_threshold_percent', 'alert_sms_template', 'alert_phone', 'created_at', 'uuid', 'updated_at', 'updated_by', 'deleted_at', 'deleted_by', 'restored_at', 'restored_by'],
    columnCount: 13,
    rowCount: 0,
  },
  crm_expenses: {
    name: 'crm_expenses',
    displayName: '지출 내역',
    columns: ['title', 'category', 'amount', 'expense_date', 'payment_method', 'attachment_url', 'ai_analysis', 'memo', 'approval_status', 'approval_memo', 'approved_at', 'actual_expense_date', 'deduction_amount', 'transfer_fee', 'created_at', 'uuid', 'updated_at', 'updated_by', 'deleted_at', 'deleted_by', 'restored_at', 'restored_by'],
    columnCount: 22,
    rowCount: 0,
  },
  inventory_logs: {
    name: 'inventory_logs',
    displayName: '재고 변동 이력',
    columns: ['itemId', 'itemName', 'itemType', 'changeType', 'quantity', 'price', 'operator', 'note', 'createdAt', 'uuid', 'updated_at', 'updated_by', 'deleted_at', 'deleted_by', 'restored_at', 'restored_by'],
    columnCount: 16,
    rowCount: 0,
  },
  alert_logs: {
    name: 'alert_logs',
    displayName: '가격 알림 발송 로그',
    columns: ['log_id', 'rule_id', 'sent_price', 'sent_message', 'sent_at', 'api_response', 'uuid', 'updated_at', 'updated_by', 'deleted_at', 'deleted_by', 'restored_at', 'restored_by'],
    columnCount: 13,
    rowCount: 0,
  },
  alert_rules: {
    name: 'alert_rules',
    displayName: '가격 알림 규칙',
    columns: ['rule_id', 'item_id', 'rule_name', 'condition_type', 'threshold_value', 'phone_number', 'sms_template', 'is_enabled', 'uuid', 'updated_at', 'updated_by', 'deleted_at', 'deleted_by', 'restored_at', 'restored_by'],
    columnCount: 15,
    rowCount: 0,
  },
  price_histories: {
    name: 'price_histories',
    displayName: '수집 가격 이력',
    columns: ['history_id', 'url_id', 'captured_price', 'captured_at', 'status', 'error_message', 'uuid', 'updated_at', 'updated_by', 'deleted_at', 'deleted_by', 'restored_at', 'restored_by'],
    columnCount: 13,
    rowCount: 0,
  },
  target_urls: {
    name: 'target_urls',
    displayName: '가격 감시 URL',
    columns: ['url_id', 'item_id', 'site_name', 'target_url', 'css_selector', 'xpath', 'cron_interval', 'is_active', 'created_at', 'uuid', 'updated_at', 'updated_by', 'deleted_at', 'deleted_by', 'restored_at', 'restored_by'],
    columnCount: 16,
    rowCount: 0,
  },
  tracked_items: {
    name: 'tracked_items',
    displayName: '가격 추적 품목',
    columns: ['item_id', 'item_code', 'item_name', 'category', 'spec', 'base_price', 'target_margin_rate', 'created_at', 'uuid', 'updated_at', 'updated_by', 'deleted_at', 'deleted_by', 'restored_at', 'restored_by'],
    columnCount: 15,
    rowCount: 0,
  },
  ai_token_usage_logs: {
    name: 'ai_token_usage_logs',
    displayName: 'AI 토큰 사용량 로그',
    columns: ['model', 'purpose', 'prompt_tokens', 'completion_tokens', 'total_tokens', 'user_name', 'menu_path', 'created_at', 'uuid', 'updated_at', 'updated_by', 'deleted_at', 'deleted_by', 'restored_at', 'restored_by'],
    columnCount: 15,
    rowCount: 0,
  },
  crm_inventory_inbound_items: {
    name: 'crm_inventory_inbound_items',
    displayName: '자율 입고 상세 품목',
    columns: ['inbound_id', 'item_name', 'spec', 'quantity', 'price', 'barcode', 'matched_item_id', 'created_at', 'uuid', 'updated_at', 'updated_by', 'deleted_at', 'deleted_by', 'restored_at', 'restored_by'],
    columnCount: 15,
    rowCount: 0,
  },
  crm_inventory_inbounds: {
    name: 'crm_inventory_inbounds',
    displayName: '자율 입고 대장',
    columns: ['partner_name', 'inbound_date', 'total_amount', 'pdf_file_path', 'created_at', 'updated_at', 'uuid', 'updated_by', 'deleted_at', 'deleted_by', 'restored_at', 'restored_by'],
    columnCount: 12,
    rowCount: 0,
  },
  inventory_items: {
    name: 'inventory_items',
    displayName: '재고 품목',
    columns: ['type', 'name', 'category', 'price', 'partner', 'stock', 'safeStock', 'location', 'spec', 'unitType', 'unitValue', 'boxContains', 'description', 'tags', 'barcode', 'createdAt', 'uuid', 'updated_at', 'updated_by', 'deleted_at', 'deleted_by', 'restored_at', 'restored_by'],
    columnCount: 23,
    rowCount: 0,
  },
  crm_partner_contacts: {
    name: 'crm_partner_contacts',
    displayName: '거래처 담당자 명함첩',
    columns: ['partner_id', 'name', 'position', 'phone', 'email', 'card_image_url', 'is_primary', 'created_at', 'uuid', 'updated_at', 'updated_by', 'deleted_at', 'deleted_by', 'restored_at', 'restored_by'],
    columnCount: 15,
    rowCount: 0,
  },
  crm_snaptask_actions: {
    name: 'crm_snaptask_actions',
    displayName: '스냅태스크 AI 액션 감사록',
    columns: ['task_id', 'action_type', 'description', 'created_at', 'uuid', 'updated_at', 'updated_by', 'deleted_at', 'deleted_by', 'restored_at', 'restored_by'],
    columnCount: 11,
    rowCount: 0,
  },
  crm_snaptask_items: {
    name: 'crm_snaptask_items',
    displayName: '스냅태스크 상세 내역',
    columns: ['task_id', 'content_text', 'file_url', 'file_type', 'ai_analysis', 'created_at', 'uuid', 'updated_at', 'updated_by', 'deleted_at', 'deleted_by', 'restored_at', 'restored_by'],
    columnCount: 13,
    rowCount: 0,
  },
  crm_snaptasks: {
    name: 'crm_snaptasks',
    displayName: '스냅태스크 관리',
    columns: ['title', 'status', 'partner_id', 'created_at', 'updated_at', 'uuid', 'updated_by', 'deleted_at', 'deleted_by', 'restored_at', 'restored_by'],
    columnCount: 11,
    rowCount: 0,
  },
  crm_partners: {
    name: 'crm_partners',
    displayName: '거래처 관리',
    columns: ['type', 'company_name', 'business_number', 'representative', 'phone', 'manager_name', 'manager_phone', 'email', 'address', 'vip_level', 'credit_limit', 'business_license_url', 'memo', 'created_at', 'uuid', 'updated_at', 'updated_by', 'deleted_at', 'deleted_by', 'restored_at', 'restored_by'],
    columnCount: 21,
    rowCount: 0,
  },
  crm_sales_orders: {
    name: 'crm_sales_orders',
    displayName: '수주서 관리',
    columns: ['estimate_id', 'client_order_no', 'customer_name', 'customer_phone', 'customer_manager', 'status', 'total_amount', 'delivery_date', 'created_at', 'uuid', 'updated_at', 'updated_by', 'deleted_at', 'deleted_by', 'restored_at', 'restored_by'],
    columnCount: 16,
    rowCount: 0,
  },
  crm_purchase_orders: {
    name: 'crm_purchase_orders',
    displayName: '발주서 관리',
    columns: ['estimate_id', 'vendor_name', 'vendor_phone', 'status', 'total_amount', 'created_at', 'completed_at', 'uuid', 'updated_at', 'updated_by', 'deleted_at', 'deleted_by', 'restored_at', 'restored_by'],
    columnCount: 14,
    rowCount: 0,
  },
  crm_estimate_items: {
    name: 'crm_estimate_items',
    displayName: '견적서 품목 상세',
    columns: ['estimate_id', 'product_id', 'product_name', 'quantity', 'unit_price', 'amount', 'uuid', 'updated_at', 'updated_by', 'deleted_at', 'deleted_by', 'restored_at', 'restored_by'],
    columnCount: 13,
    rowCount: 0,
  },
  crm_estimates: {
    name: 'crm_estimates',
    displayName: '견적서 관리',
    columns: ['type', 'direction_status', 'partner_name', 'partner_phone', 'partner_manager', 'tags', 'total_amount', 'file_url', 'business_license_url', 'ai_parsed', 'created_at', 'uuid', 'sales_order_number', 'purchase_order_number', 'updated_at', 'updated_by', 'deleted_at', 'deleted_by', 'restored_at', 'restored_by'],
    columnCount: 20,
    rowCount: 0,
  },
  crm_point_history: {
    name: 'crm_point_history',
    displayName: '적립금 내역',
    columns: ['customer_id', 'transaction_type', 'amount', 'balance_after', 'description', 'related_entity_type', 'related_entity_id', 'created_at', 'uuid', 'updated_at', 'updated_by', 'deleted_at', 'deleted_by', 'restored_at', 'restored_by'],
    columnCount: 15,
    rowCount: 0,
  },
  crm_coupons_restrictions: {
    name: 'crm_coupons_restrictions',
    displayName: '쿠폰 제한 관리',
    columns: ['coupon_id', 'restriction_type', 'target_type', 'target_value', 'created_at', 'uuid', 'updated_at', 'updated_by', 'deleted_at', 'deleted_by', 'restored_at', 'restored_by'],
    columnCount: 12,
    rowCount: 0,
  },
  coupons: {
    name: 'coupons',
    displayName: '쿠폰 관리',
    columns: ['code', 'name', 'discount_type', 'discount_value', 'min_order_amount', 'status', 'expires_at', 'created_at', 'uuid', 'updated_at', 'updated_by', 'deleted_at', 'deleted_by', 'restored_at', 'restored_by'],
    columnCount: 15,
    rowCount: 0,
  },
  naver_blog_marketing_settings: {
    name: 'naver_blog_marketing_settings',
    displayName: '네이버 블로그 마케팅 설정',
    columns: ['is_autopilot', 'autopilot_interval', 'autopilot_time', 'tone_style', 'naver_blog_id', 'api_client_id', 'api_client_secret', 'uuid', 'updated_at', 'updated_by', 'deleted_at', 'deleted_by', 'restored_at', 'restored_by'],
    columnCount: 14,
    rowCount: 0,
  },
  crm_naver_blog_posts: {
    name: 'crm_naver_blog_posts',
    displayName: '네이버 블로그 포스팅 이력 및 예약',
    columns: ['product_id', 'status', 'title', 'content', 'target_keywords', 'image_url', 'sub_image_url', 'scheduled_at', 'posted_at', 'error_message', 'views_count', 'likes_count', 'uuid', 'updated_at', 'updated_by', 'deleted_at', 'deleted_by', 'restored_at', 'restored_by'],
    columnCount: 19,
    rowCount: 0,
  },
  instagram_marketing_settings: {
    name: 'instagram_marketing_settings',
    displayName: '인스타그램 마케팅 설정',
    columns: ['is_autopilot', 'autopilot_interval', 'autopilot_time', 'tone_style', 'instagram_username', 'access_token', 'uuid', 'updated_at', 'updated_by', 'deleted_at', 'deleted_by', 'restored_at', 'restored_by'],
    columnCount: 13,
    rowCount: 0,
  },
  crm_instagram_posts: {
    name: 'crm_instagram_posts',
    displayName: '인스타그램 포스팅 이력 및 예약',
    columns: ['product_id', 'status', 'content', 'image_url', 'scheduled_at', 'posted_at', 'error_message', 'likes_count', 'comments_count', 'uuid', 'updated_at', 'updated_by', 'deleted_at', 'deleted_by', 'restored_at', 'restored_by'],
    columnCount: 16,
    rowCount: 0,
  },
  crm_operators: {
    name: 'crm_operators',
    displayName: '운영자 권한 관리',
    columns: ['username', 'password_hash', 'name', 'role', 'created_at', 'uuid', 'updated_at', 'updated_by', 'deleted_at', 'deleted_by', 'restored_at', 'restored_by'],
    columnCount: 12,
    rowCount: 0,
  },
  crm_deliveries: {
    name: 'crm_deliveries',
    displayName: '배송 내역',
    columns: ['customer_name', 'customer_phone', 'address', 'courier', 'tracking_number', 'status', 'order_id', 'uuid', 'updated_at', 'updated_by', 'deleted_at', 'deleted_by', 'restored_at', 'restored_by'],
    columnCount: 14,
    rowCount: 0,
  },
  crm_reservations: {
    name: 'crm_reservations',
    displayName: '예약 내역',
    columns: ['customer_name', 'customer_phone', 'service_name', 'reservation_date', 'reservation_time', 'status', 'uuid', 'updated_at', 'updated_by', 'deleted_at', 'deleted_by', 'restored_at', 'restored_by'],
    columnCount: 13,
    rowCount: 0,
  },
  crm_payments: {
    name: 'crm_payments',
    displayName: '결제 내역',
    columns: ['customer_name', 'payment_method', 'amount', 'payment_date', 'status', 'order_id', 'uuid', 'updated_at', 'updated_by', 'deleted_at', 'deleted_by', 'restored_at', 'restored_by'],
    columnCount: 13,
    rowCount: 0,
  },
  crm_orders: {
    name: 'crm_orders',
    displayName: '주문 내역',
    columns: ['customer_name', 'customer_phone', 'product_name', 'quantity', 'total_price', 'delivery_method', 'shipping_address', 'tracking_number', 'attachment_url', 'customer_memo', 'order_date', 'status', 'uuid', 'updated_at', 'updated_by', 'deleted_at', 'deleted_by', 'restored_at', 'restored_by'],
    columnCount: 19,
    rowCount: 0,
  },
  crm_transactions: {
    name: 'crm_transactions',
    displayName: '거래 내역',
    columns: ['customer_name', 'customer_phone', 'product_name', 'amount', 'order_date', 'status', 'order_id', 'uuid', 'updated_at', 'updated_by', 'deleted_at', 'deleted_by', 'restored_at', 'restored_by'],
    columnCount: 14,
    rowCount: 0,
  },
  products: {
    name: 'products',
    displayName: '광고 상품',
    columns: ['name', 'price', 'url', 'description', 'main_image_url', 'detail_image_url', 'available_methods', 'category', 'menu_category', 'is_coupon_excludable', 'is_estimate_price', 'uuid', 'updated_at', 'updated_by', 'deleted_at', 'deleted_by', 'restored_at', 'restored_by'],
    columnCount: 18,
    rowCount: 0,
  },
  ad_templates: {
    name: 'ad_templates',
    displayName: '광고 템플릿',
    columns: ['name', 'header', 'footer', 'opt_out', 'uuid', 'updated_at', 'updated_by', 'deleted_at', 'deleted_by', 'restored_at', 'restored_by'],
    columnCount: 11,
    rowCount: 0,
  },
  message_logs: {
    name: 'message_logs',
    displayName: '발송 내역',
    columns: ['customer_id', 'phone', 'message', 'status', 'created_at', 'uuid', 'updated_at', 'updated_by', 'deleted_at', 'deleted_by', 'restored_at', 'restored_by'],
    columnCount: 12,
    rowCount: 0,
  },
  message_templates: {
    name: 'message_templates',
    displayName: '문자 템플릿',
    columns: ['title', 'content', 'uuid', 'updated_at', 'updated_by', 'deleted_at', 'deleted_by', 'restored_at', 'restored_by'],
    columnCount: 9,
    rowCount: 0,
  },
  crm_web_form_logs: {
    name: 'crm_web_form_logs',
    displayName: '웹 양식 발급대장',
    columns: ['template_id', 'record_id', 'record_name', 'print_data', 'issue_date', 'uuid', 'updated_at', 'updated_by', 'deleted_at', 'deleted_by', 'restored_at', 'restored_by'],
    columnCount: 12,
    rowCount: 0,
  },
  crm_web_templates: {
    name: 'crm_web_templates',
    displayName: '웹 양식 템플릿 마스터',
    columns: ['template_name', 'html_content', 'web_html_content', 'document_type', 'is_active', 'is_print_active', 'is_web_active', 'uuid', 'updated_at', 'updated_by', 'deleted_at', 'deleted_by', 'restored_at', 'restored_by'],
    columnCount: 14,
    rowCount: 0,
  },
  system_settings: {
    name: 'system_settings',
    displayName: '시스템 설정',
    columns: ['key', 'value', 'uuid', 'updated_at', 'updated_by', 'deleted_at', 'deleted_by', 'restored_at', 'restored_by'],
    columnCount: 9,
    rowCount: 0,
  },
  crm_customers: {
    name: 'crm_customers',
    displayName: '고객 명단',
    columns: ['name', 'phone', 'tags', 'memo', 'address', 'shipping_address', 'recipient_name', 'recipient_phone', 'point_balance', 'created_at', 'uuid', 'updated_at', 'updated_by', 'deleted_at', 'deleted_by', 'restored_at', 'restored_by'],
    columnCount: 17,
    rowCount: 0,
  },
  crm_finance_forecasts: {
    name: 'crm_finance_forecasts',
    displayName: '수금 및 지출 예정 대장',
    columns: ['date', 'type', 'title', 'partnerName', 'amount', 'isOverdue', 'contact', 'uuid', 'updated_at', 'updated_by', 'deleted_at', 'deleted_by', 'restored_at', 'restored_by'],
    columnCount: 14,
    rowCount: 0,
  },
  crm_finance_products: {
    name: 'crm_finance_products',
    displayName: '제품 원가 기초 데이터',
    columns: ['productId', 'productName', 'rawMaterialCost', 'laborCost', 'expenseCost', 'sellingPrice', 'uuid', 'updated_at', 'updated_by', 'deleted_at', 'deleted_by', 'restored_at', 'restored_by'],
    columnCount: 13,
    rowCount: 0,
  },
  crm_facility_layout: {
    name: 'crm_facility_layout',
    displayName: '공장 설비 평면 배치 및 상태',
    columns: ['name', 'status', 'oee', 'x', 'y', 'uuid', 'updated_at', 'updated_by', 'deleted_at', 'deleted_by', 'restored_at', 'restored_by'],
    columnCount: 12,
    rowCount: 0,
  },
  crm_facility_oee_downtime: {
    name: 'crm_facility_oee_downtime',
    displayName: '비가동 원인 통계',
    columns: ['reason', 'minutes', 'rate', 'uuid', 'updated_at', 'updated_by', 'deleted_at', 'deleted_by', 'restored_at', 'restored_by'],
    columnCount: 10,
    rowCount: 0,
  },
  crm_facility_oee_stats: {
    name: 'crm_facility_oee_stats',
    displayName: 'OEE 설비 종합 효율 통계',
    columns: ['overallOee', 'availability', 'performance', 'quality', 'totalLoaded', 'actualRun', 'plannedStop', 'breakdownStop', 'opportunityLossKrw', 'preventedLossKrw', 'uuid', 'updated_at', 'updated_by', 'deleted_at', 'deleted_by', 'restored_at', 'restored_by'],
    columnCount: 17,
    rowCount: 0,
  },
  crm_facility_parts: {
    name: 'crm_facility_parts',
    displayName: '소모성 부품 재고 관리',
    columns: ['name', 'safetyStock', 'currentStock', 'unit', 'leadTimeDays', 'risk', 'uuid', 'updated_at', 'updated_by', 'deleted_at', 'deleted_by', 'restored_at', 'restored_by'],
    columnCount: 13,
    rowCount: 0,
  },
  crm_facility_events: {
    name: 'crm_facility_events',
    displayName: '월간 정비 일정',
    columns: ['date', 'title', 'type', 'assignee', 'uuid', 'updated_at', 'updated_by', 'deleted_at', 'deleted_by', 'restored_at', 'restored_by'],
    columnCount: 11,
    rowCount: 0,
  },
  crm_production_due_risk: {
    name: 'crm_production_due_risk',
    displayName: '납기 준수 위험 분석',
    columns: ['orderId', 'productName', 'probability', 'status', 'uuid', 'updated_at', 'updated_by', 'deleted_at', 'deleted_by', 'restored_at', 'restored_by'],
    columnCount: 11,
    rowCount: 0,
  },
  crm_production_bottlenecks: {
    name: 'crm_production_bottlenecks',
    displayName: '설비별 누적 로드 및 병목 지수',
    columns: ['name', 'loadRate', 'status', 'queueTasks', 'uuid', 'updated_at', 'updated_by', 'deleted_at', 'deleted_by', 'restored_at', 'restored_by'],
    columnCount: 11,
    rowCount: 0,
  },
  crm_production_unscheduled_orders: {
    name: 'crm_production_unscheduled_orders',
    displayName: '미배정 수주 대장',
    columns: ['orderId', 'productName', 'qty', 'dueDate', 'status', 'uuid', 'updated_at', 'updated_by', 'deleted_at', 'deleted_by', 'restored_at', 'restored_by'],
    columnCount: 12,
    rowCount: 0,
  },
  crm_production_gantt_tasks: {
    name: 'crm_production_gantt_tasks',
    displayName: '생산 간트 차트 작업 목록',
    columns: ['title', 'equipmentId', 'equipmentName', 'operatorName', 'startHour', 'endHour', 'progress', 'status', 'uuid', 'updated_at', 'updated_by', 'deleted_at', 'deleted_by', 'restored_at', 'restored_by'],
    columnCount: 15,
    rowCount: 0,
  },
  crm_partner_credit_risks: {
    name: 'crm_partner_credit_risks',
    displayName: '거래처 신용 위험 및 연체 지표 대장',
    columns: ['overdue_amount', 'overdue_days', 'credit_rating', 'default_probability', 'risk_level', 'last_action', 'action_date', 'uuid', 'updated_at', 'updated_by', 'deleted_at', 'deleted_by', 'restored_at', 'restored_by'],
    columnCount: 14,
    rowCount: 0,
  },
  crm_labor_contracts: {
    name: 'crm_labor_contracts',
    displayName: '근로계약서 독소조항 스캔 현황',
    columns: ['clause_id', 'title', 'is_illegal', 'current_text', 'recommended_text', 'reason', 'uuid', 'updated_at', 'updated_by', 'deleted_at', 'deleted_by', 'restored_at', 'restored_by'],
    columnCount: 13,
    rowCount: 0,
  },
  crm_labor_stats: {
    name: 'crm_labor_stats',
    displayName: '임직원 근태 리스크 요약',
    columns: ['weekly_hours', 'overtime_hours', 'lateness_count', 'early_leave_count', 'risk_level', 'uuid', 'updated_at', 'updated_by', 'deleted_at', 'deleted_by', 'restored_at', 'restored_by'],
    columnCount: 12,
    rowCount: 0,
  },
  crm_scm_suppliers: {
    name: 'crm_scm_suppliers',
    displayName: '협력사 스코어카드',
    columns: ['supplier_name', 'delivery_rate', 'defect_rate', 'score', 'uuid', 'updated_at', 'updated_by', 'deleted_at', 'deleted_by', 'restored_at', 'restored_by'],
    columnCount: 11,
    rowCount: 0,
  },
  crm_scm_shipments: {
    name: 'crm_scm_shipments',
    displayName: '실시간 수입 조달 화물 리스트',
    columns: ['item_name', 'supplier_name', 'status', 'eta', 'delay_probability', 'current_step', 'uuid', 'updated_at', 'updated_by', 'deleted_at', 'deleted_by', 'restored_at', 'restored_by'],
    columnCount: 13,
    rowCount: 0,
  },
  crm_safety_zones: {
    name: 'crm_safety_zones',
    displayName: '안전 제어 구역 설정',
    columns: ['zone_name', 'risk_score', 'status', 'uuid', 'updated_at', 'updated_by', 'deleted_at', 'deleted_by', 'restored_at', 'restored_by'],
    columnCount: 10,
    rowCount: 0,
  },
  crm_safety_alerts: {
    name: 'crm_safety_alerts',
    displayName: 'CCTV 비상 위험 알림 로그',
    columns: ['zone_name', 'alert_level', 'detector_type', 'created_at', 'is_resolved', 'uuid', 'updated_at', 'updated_by', 'deleted_at', 'deleted_by', 'restored_at', 'restored_by'],
    columnCount: 12,
    rowCount: 0,
  },
  crm_energy_equipments: {
    name: 'crm_energy_equipments',
    displayName: '에너지 소모 설비 대장',
    columns: ['equipment_name', 'status', 'current_load', 'monthly_bill', 'uuid', 'updated_at', 'updated_by', 'deleted_at', 'deleted_by', 'restored_at', 'restored_by'],
    columnCount: 11,
    rowCount: 0,
  },
  crm_energy_savings: {
    name: 'crm_energy_savings',
    displayName: '에너지 절감 스케줄',
    columns: ['apply_date', 'saving_amount', 'is_active', 'uuid', 'updated_at', 'updated_by', 'deleted_at', 'deleted_by', 'restored_at', 'restored_by'],
    columnCount: 10,
    rowCount: 0,
  },
  pms_projects: {
    name: 'pms_projects',
    displayName: 'PMS 프로젝트 대장',
    columns: ['client', 'bizNo', 'name', 'type', 'dueDate', 'folderUrl', 'estimateUrl', 'status', 'createdAt', 'details', 'processStep', 'inboundChannel', 'uuid', 'updated_at', 'updated_by', 'deleted_at', 'deleted_by', 'restored_at', 'restored_by'],
    columnCount: 19,
    rowCount: 0,
  },
  ecount_rpa_lock: {
    name: 'ecount_rpa_lock',
    displayName: '이카운트 RPA 실행 락',
    columns: ['is_locked', 'locked_by', 'locked_at', 'cooldown_until', 'uuid', 'updated_at', 'updated_by', 'deleted_at', 'deleted_by', 'restored_at', 'restored_by'],
    columnCount: 11,
    rowCount: 0,
  },
  ecount_sync_schedules: {
    name: 'ecount_sync_schedules',
    displayName: '이카운트 ERP 동기화 스케줄',
    columns: ['script_file', 'script_title', 'target_table', 'period_preset', 'run_time', 'is_active', 'last_run_at', 'next_run_at', 'created_at', 'uuid', 'updated_at', 'updated_by', 'deleted_at', 'deleted_by', 'restored_at', 'restored_by'],
    columnCount: 16,
    rowCount: 0,
  },
  crm_company_event_types: {
    name: 'crm_company_event_types',
    displayName: '회사 일정 유형 마스터 대장',
    columns: ['type_key', 'type_name', 'color_theme', 'is_system', 'created_at', 'updated_at', 'uuid', 'updated_by', 'deleted_at', 'deleted_by', 'restored_at', 'restored_by'],
    columnCount: 12,
    rowCount: 0,
  },
  crm_operator_ai_briefing_histories: {
    name: 'crm_operator_ai_briefing_histories',
    displayName: '임직원 AI 전사 업무 분석 이력 대장',
    columns: ['target_year_month', 'risk_score', 'alert_title', 'alert_message', 'briefing_text', 'created_at', 'created_by', 'token_usage_input', 'token_usage_output', 'uuid', 'updated_at', 'updated_by', 'deleted_at', 'deleted_by', 'restored_at', 'restored_by'],
    columnCount: 16,
    rowCount: 0,
  },
  crm_operator_projects: {
    name: 'crm_operator_projects',
    displayName: '임직원 참여 프로젝트 대장',
    columns: ['operator_id', 'project_name', 'role_in_project', 'start_date', 'end_date', 'contribution_rate', 'performance_score', 'performance_evaluation', 'outcome_link', 'uuid', 'updated_at', 'updated_by', 'deleted_at', 'deleted_by', 'restored_at', 'restored_by'],
    columnCount: 16,
    rowCount: 0,
  },
  crm_operator_job_history: {
    name: 'crm_operator_job_history',
    displayName: '임직원 담당업무 변경이력 대장',
    columns: ['operator_id', 'assignment_date', 'job_description', 'prev_job_description', 'is_current', 'uuid', 'updated_at', 'updated_by', 'deleted_at', 'deleted_by', 'restored_at', 'restored_by'],
    columnCount: 12,
    rowCount: 0,
  },
  crm_operator_families: {
    name: 'crm_operator_families',
    displayName: '임직원 부양가족 대장',
    columns: ['operator_id', 'relation_type', 'name', 'birth_date', 'phone_number', 'is_dependent', 'remarks', 'uuid', 'updated_at', 'updated_by', 'deleted_at', 'deleted_by', 'restored_at', 'restored_by'],
    columnCount: 14,
    rowCount: 0,
  },
  crm_operator_reputations: {
    name: 'crm_operator_reputations',
    displayName: '임직원 다차원 평판 대장',
    columns: ['operator_id', 'evaluation_date', 'evaluator_id', 'source_type', 'score', 'positive_feedback', 'constructive_feedback', 'updated_at', 'uuid', 'updated_by', 'deleted_at', 'deleted_by', 'restored_at', 'restored_by'],
    columnCount: 14,
    rowCount: 0,
  },
  crm_operator_incidents: {
    name: 'crm_operator_incidents',
    displayName: '임직원 대내외 사건사고 대장',
    columns: ['operator_id', 'occurred_date', 'severity', 'title', 'description', 'status', 'outcome', 'updated_at', 'uuid', 'updated_by', 'deleted_at', 'deleted_by', 'restored_at', 'restored_by'],
    columnCount: 14,
    rowCount: 0,
  },
  crm_operator_medical: {
    name: 'crm_operator_medical',
    displayName: '임직원 병력 치료 대장',
    columns: ['operator_id', 'diagnosis_name', 'treatment_start_date', 'treatment_end_date', 'hospital_name', 'sick_leave_days', 'work_limitations', 'uuid', 'updated_at', 'updated_by', 'deleted_at', 'deleted_by', 'restored_at', 'restored_by'],
    columnCount: 14,
    rowCount: 0,
  },
  crm_operator_family_events: {
    name: 'crm_operator_family_events',
    displayName: '임직원 경조사 지원 대장',
    columns: ['operator_id', 'event_date', 'relation', 'type', 'congratulation_money', 'wreath_provided', 'uuid', 'updated_at', 'updated_by', 'deleted_at', 'deleted_by', 'restored_at', 'restored_by'],
    columnCount: 13,
    rowCount: 0,
  },
  crm_operator_awards: {
    name: 'crm_operator_awards',
    displayName: '임직원 상벌 징계 대장',
    columns: ['operator_id', 'record_date', 'type', 'title', 'content', 'authority', 'remarks', 'uuid', 'updated_at', 'updated_by', 'deleted_at', 'deleted_by', 'restored_at', 'restored_by'],
    columnCount: 14,
    rowCount: 0,
  },
  crm_operator_promotions: {
    name: 'crm_operator_promotions',
    displayName: '임직원 승진발령 대장',
    columns: ['operator_id', 'change_date', 'prev_dept', 'next_dept', 'prev_role', 'next_role', 'promotion_reason', 'uuid', 'updated_at', 'updated_by', 'deleted_at', 'deleted_by', 'restored_at', 'restored_by'],
    columnCount: 14,
    rowCount: 0,
  },
  crm_operator_salaries: {
    name: 'crm_operator_salaries',
    displayName: '임직원 급여상여 이력 대장',
    columns: ['operator_id', 'payment_year_month', 'base_salary', 'bonus_amount', 'weekly_holiday_allowance', 'overtime_allowance', 'meal_allowance', 'deduction_amount', 'net_salary', 'payment_date', 'status', 'uuid', 'updated_at', 'updated_by', 'deleted_at', 'deleted_by', 'restored_at', 'restored_by'],
    columnCount: 18,
    rowCount: 0,
  },
  crm_operator_careers: {
    name: 'crm_operator_careers',
    displayName: '임직원 이전경력 대장',
    columns: ['operator_id', 'company_name', 'department', 'job_title', 'join_date', 'retire_date', 'assigned_task', 'leaving_reason', 'uuid', 'updated_at', 'updated_by', 'deleted_at', 'deleted_by', 'restored_at', 'restored_by'],
    columnCount: 15,
    rowCount: 0,
  },
  crm_operator_licenses: {
    name: 'crm_operator_licenses',
    displayName: '임직원 자격면허 대장',
    columns: ['operator_id', 'license_name', 'issuer', 'license_no', 'acquisition_date', 'expiry_date', 'uuid', 'updated_at', 'updated_by', 'deleted_at', 'deleted_by', 'restored_at', 'restored_by'],
    columnCount: 13,
    rowCount: 0,
  },
  crm_operator_education: {
    name: 'crm_operator_education',
    displayName: '임직원 학력이력 대장',
    columns: ['operator_id', 'school_name', 'major', 'degree', 'entrance_date', 'graduation_date', 'status', 'uuid', 'updated_at', 'updated_by', 'deleted_at', 'deleted_by', 'restored_at', 'restored_by'],
    columnCount: 14,
    rowCount: 0,
  },
  crm_operator_profiles: {
    name: 'crm_operator_profiles',
    displayName: '임직원 인적사항 상세 대장',
    columns: ['operator_id', 'department', 'hire_date', 'commute_area', 'skills', 'backup_operator_id', 'updated_at', 'uuid', 'updated_by', 'deleted_at', 'deleted_by', 'restored_at', 'restored_by'],
    columnCount: 13,
    rowCount: 0,
  },
  crm_operator_contract_settings: {
    name: 'crm_operator_contract_settings',
    displayName: '임직원 근로 계약 조건 대장',
    columns: ['operator_id', 'hourly_wage', 'weekly_hours', 'allow_weekly_holiday_paid', 'work_days', 'contract_memo', 'updated_at', 'uuid', 'updated_by', 'deleted_at', 'deleted_by', 'restored_at', 'restored_by'],
    columnCount: 13,
    rowCount: 0,
  },
  crm_company_events: {
    name: 'crm_company_events',
    displayName: '전사 회사 일정 공유 대장',
    columns: ['title', 'start_date', 'end_date', 'event_type', 'description', 'created_by', 'created_at', 'uuid', 'updated_at', 'updated_by', 'deleted_at', 'deleted_by', 'restored_at', 'restored_by'],
    columnCount: 14,
    rowCount: 0,
  },
  crm_operator_leave_balances: {
    name: 'crm_operator_leave_balances',
    displayName: '직원별 연차 잔액 관리',
    columns: ['operator_id', 'total_allowed', 'used', 'remaining', 'updated_at', 'uuid', 'updated_by', 'deleted_at', 'deleted_by', 'restored_at', 'restored_by'],
    columnCount: 11,
    rowCount: 0,
  },
  crm_annual_leaves: {
    name: 'crm_annual_leaves',
    displayName: '직원 연차 신청 결재 대장',
    columns: ['operator_id', 'leave_type', 'start_date', 'end_date', 'days_spent', 'status', 'reason', 'reject_reason', 'approver_id', 'created_at', 'updated_at', 'uuid', 'updated_by', 'deleted_at', 'deleted_by', 'restored_at', 'restored_by'],
    columnCount: 17,
    rowCount: 0,
  },
  crm_attendance: {
    name: 'crm_attendance',
    displayName: '직원 근태 대장',
    columns: ['operator_id', 'work_date', 'clock_in', 'clock_out', 'status', 'working_hours', 'memo', 'created_at', 'updated_at', 'uuid', 'updated_by', 'deleted_at', 'deleted_by', 'restored_at', 'restored_by'],
    columnCount: 15,
    rowCount: 0,
  },
  user_feedbacks: {
    name: 'user_feedbacks',
    displayName: '사용자 피드백 및 버그 제보',
    columns: ['user_prompt', 'detected_type', 'current_url', 'resolved_status', 'created_at', 'uuid', 'updated_at', 'updated_by', 'deleted_at', 'deleted_by', 'restored_at', 'restored_by'],
    columnCount: 12,
    rowCount: 0,
  },
  tenant_menu_settings: {
    name: 'tenant_menu_settings',
    displayName: '테넌트 메뉴 설정',
    columns: ['tenant_id', 'menu_href', 'is_enabled', 'sort_order', 'uuid', 'updated_at', 'updated_by', 'deleted_at', 'deleted_by', 'restored_at', 'restored_by'],
    columnCount: 11,
    rowCount: 0,
  },
  exchange_rate_histories: {
    name: 'exchange_rate_histories',
    displayName: '환율 변동 이력',
    columns: ['history_id', 'currency_code', 'rate_value', 'captured_date', 'uuid', 'updated_at', 'updated_by', 'deleted_at', 'deleted_by', 'restored_at', 'restored_by'],
    columnCount: 11,
    rowCount: 0,
  },
  exchange_rates: {
    name: 'exchange_rates',
    displayName: '실시간 환율',
    columns: ['rate_id', 'currency_code', 'currency_name', 'current_rate', 'change_rate', 'change_direction', 'last_updated_at', 'uuid', 'updated_at', 'updated_by', 'deleted_at', 'deleted_by', 'restored_at', 'restored_by'],
    columnCount: 14,
    rowCount: 0,
  },
  crm_meetings: {
    name: 'crm_meetings',
    displayName: '회의 대장',
    columns: ['id', 'title', 'date', 'attendees', 'transcript', 'summary', 'status', 'audio_url', 'uuid', 'updated_at', 'updated_by', 'deleted_at', 'deleted_by', 'restored_at', 'restored_by'],
    columnCount: 15,
    rowCount: 0,
  },
  crm_meeting_tasks: {
    name: 'crm_meeting_tasks',
    displayName: '회의 할 일 및 일정',
    columns: ['id', 'meeting_id', 'assignee_name', 'assignee_email', 'task_desc', 'due_date', 'status', 'uuid', 'updated_at', 'updated_by', 'deleted_at', 'deleted_by', 'restored_at', 'restored_by'],
    columnCount: 14,
    rowCount: 0,
  },
} as const;

export type TableName = keyof typeof TABLES;
export const TABLE_NAMES = Object.keys(TABLES) as TableName[];
